# version: "3.8"

services:
  secretr_vault1:
    build: .
    container_name: secretr_vault1
    ports:
      - "8200:8200"
    networks:
      - secretr-net
    volumes:
      - ./vault.key:/vault/vault.key:ro    # User must create this.
      # - ./store.enc:/vault/store.enc
      - ./vault-data:/vault/data           # store.enc will be created here.
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128M"
        reservations:
          cpus: "0.10"
          memory: "64M"

networks:
  secretr-net:
    external: true
